services:
  backend:
    build: ./backend
    container_name: earthquake-backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: earthquake-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always